# Generated by Django 4.1.3 on 2024-05-02 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="course",
            fields=[
                ("course_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "course_code",
                    models.CharField(blank=True, default=None, max_length=128),
                ),
                (
                    "course_name",
                    models.CharField(blank=True, default=None, max_length=128),
                ),
                (
                    "course_name_eng",
                    models.CharField(blank=True, default=None, max_length=128),
                ),
                ("active", models.IntegerField(default=1)),
                ("crt_date", models.DateTimeField(blank=True, null=True)),
                ("upd_date", models.DateTimeField(blank=True, null=True)),
                ("cancelled", models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="course_event",
            fields=[
                ("ev_id", models.AutoField(primary_key=True, serialize=False)),
                ("ev_date_start", models.DateField(blank=True, null=True)),
                ("ev_date_end", models.DateField(blank=True, null=True)),
                ("ev_generation", models.IntegerField(default=0)),
                (
                    "ev_remark",
                    models.CharField(blank=True, default=None, max_length=256),
                ),
                ("ev_price", models.FloatField(default=0)),
                ("ev_vat", models.IntegerField(default=0)),
                ("ev_expired_cer_quantity", models.IntegerField(default=0)),
                ("ev_expired_cer_date", models.DateField(blank=True, null=True)),
                ("ev_logo", models.ImageField(default=None, upload_to="images/logo")),
                ("active", models.IntegerField(default=1)),
                ("crt_date", models.DateTimeField(blank=True, null=True)),
                ("upd_date", models.DateTimeField(blank=True, null=True)),
                ("cancelled", models.IntegerField(default=1)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.course"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="location_thai",
            fields=[
                ("location_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "district_code",
                    models.CharField(blank=True, default=None, max_length=128),
                ),
                (
                    "district_name",
                    models.CharField(blank=True, default=None, max_length=128),
                ),
                ("zipcode", models.CharField(blank=True, default=None, max_length=128)),
                (
                    "amphur_code",
                    models.CharField(blank=True, default=None, max_length=128),
                ),
                (
                    "amphur_name",
                    models.CharField(blank=True, default=None, max_length=128),
                ),
                (
                    "province_code",
                    models.CharField(blank=True, default=None, max_length=128),
                ),
                (
                    "province_name",
                    models.CharField(blank=True, default=None, max_length=128),
                ),
            ],
        ),
        migrations.CreateModel(
            name="register_main",
            fields=[
                (
                    "register_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "register_number",
                    models.CharField(blank=True, default=None, max_length=64),
                ),
                ("customer_type", models.IntegerField(default=0)),
                ("customer_status", models.IntegerField(default=0)),
                ("pay_type", models.IntegerField(default=0)),
                ("pay_status", models.IntegerField(default=0)),
                ("close_the_sale", models.IntegerField(default=0)),
                ("crt_date", models.DateTimeField(blank=True, null=True)),
                ("upd_date", models.DateTimeField(blank=True, null=True)),
                (
                    "ev",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.course_event",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_create",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_update",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_update",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="register_payment",
            fields=[
                ("rp_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "rp_doc_number",
                    models.CharField(blank=True, default=None, max_length=128),
                ),
                (
                    "rp_code_customer",
                    models.CharField(blank=True, default=None, max_length=128),
                ),
                (
                    "rp_name_customer",
                    models.CharField(blank=True, default=None, max_length=128),
                ),
                ("rp_tax", models.CharField(blank=True, default=None, max_length=128)),
                (
                    "rp_name_seller",
                    models.CharField(blank=True, default=None, max_length=128),
                ),
                (
                    "rp_name_contact",
                    models.CharField(blank=True, default=None, max_length=128),
                ),
                (
                    "rp_branch",
                    models.CharField(blank=True, default=None, max_length=128),
                ),
                (
                    "rp_address",
                    models.CharField(blank=True, default=None, max_length=512),
                ),
                ("rp_phone", models.CharField(blank=True, default=None, max_length=64)),
                ("rp_email", models.CharField(blank=True, default=None, max_length=64)),
                ("rp_confirm_date_price", models.DateField(blank=True, null=True)),
                ("rp_date_delivery", models.DateField(blank=True, null=True)),
                ("rp_quota", models.IntegerField(default=0)),
                ("rp_ref1", models.CharField(blank=True, default=None, max_length=128)),
                ("rp_ref2", models.CharField(blank=True, default=None, max_length=128)),
                ("active", models.IntegerField(default=1)),
                ("crt_date", models.DateTimeField(blank=True, null=True)),
                ("upd_date", models.DateTimeField(blank=True, null=True)),
                (
                    "register",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.register_main",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="student",
            fields=[
                (
                    "student_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "student_identification_number",
                    models.CharField(blank=True, default=None, max_length=24),
                ),
                (
                    "student_prefix_th",
                    models.CharField(blank=True, default=None, max_length=12),
                ),
                (
                    "student_firstname_th",
                    models.CharField(blank=True, default=None, max_length=128),
                ),
                (
                    "student_lastname_th",
                    models.CharField(blank=True, default=None, max_length=128),
                ),
                (
                    "student_prefix_eng",
                    models.CharField(blank=True, default=None, max_length=12),
                ),
                (
                    "student_firstname_eng",
                    models.CharField(blank=True, default=None, max_length=128),
                ),
                (
                    "student_lastname_eng",
                    models.CharField(blank=True, default=None, max_length=128),
                ),
                ("student_learning_status", models.IntegerField(default=0)),
                (
                    "student_code",
                    models.CharField(blank=True, default=None, max_length=64),
                ),
                ("crt_date", models.DateTimeField(blank=True, null=True)),
                ("upd_date", models.DateTimeField(blank=True, null=True)),
                (
                    "register",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_register",
                        to="app.register_main",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="register_ref",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ref", models.CharField(blank=True, default=None, max_length=128)),
                ("crt_date", models.DateTimeField(blank=True, null=True)),
                (
                    "register",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ref_create",
                        to="app.register_main",
                    ),
                ),
                (
                    "user_crt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="register_payment_items",
            fields=[
                ("rpi_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "rpi_code",
                    models.CharField(blank=True, default=None, max_length=128),
                ),
                (
                    "rpi_name",
                    models.CharField(blank=True, default=None, max_length=128),
                ),
                ("rpi_quantity", models.IntegerField(default=0)),
                ("rpi_unit", models.CharField(blank=True, default=None, max_length=64)),
                ("rpi_price", models.FloatField(default=0)),
                ("rpi_price_discount", models.FloatField(default=0)),
                ("rpi_price_total", models.FloatField(default=0)),
                ("rpi_price_vat", models.FloatField(default=0)),
                ("rpi_price_result", models.FloatField(default=0)),
                ("rpi_pay", models.FloatField(default=0)),
                (
                    "register",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.register_main",
                    ),
                ),
                (
                    "rp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.register_payment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="register_applove",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.IntegerField(default=0)),
                ("doc_type", models.IntegerField(default=0)),
                ("complete", models.IntegerField(default=0)),
                ("remark", models.CharField(blank=True, default=None, max_length=128)),
                ("crt_date", models.DateTimeField(blank=True, null=True)),
                (
                    "register",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.register_main",
                    ),
                ),
                (
                    "user_approve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regis_user_approve",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_crt",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_crt_approve",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="pos_machine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pm_id_code",
                    models.CharField(blank=True, default=None, max_length=64),
                ),
                (
                    "pm_id_number",
                    models.CharField(blank=True, default=None, max_length=64),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="customers",
            fields=[
                ("customer_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "customer_code",
                    models.CharField(blank=True, default=None, max_length=128),
                ),
                (
                    "customer_name",
                    models.CharField(blank=True, default=None, max_length=256),
                ),
                (
                    "customer_tax",
                    models.CharField(blank=True, default=None, max_length=64),
                ),
                (
                    "customer_phone",
                    models.CharField(blank=True, default=None, max_length=64),
                ),
                (
                    "customer_email",
                    models.CharField(blank=True, default=None, max_length=64),
                ),
                (
                    "customer_address",
                    models.CharField(blank=True, default=None, max_length=512),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.location_thai",
                    ),
                ),
                (
                    "register",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.register_main",
                    ),
                ),
            ],
        ),
    ]
