# Generated by Django 4.1.3 on 2024-06-11 20:33

import app.functions
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="billing_cycle_setting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bcs_start_day", models.IntegerField(default=0)),
                ("bcs_end_day", models.IntegerField(default=0)),
                ("module", models.CharField(blank=True, default="tz", max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name="category_program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cm_name", models.CharField(blank=True, default=None, max_length=128)),
                ("active", models.IntegerField(default=1)),
                ("cancelled", models.IntegerField(default=1)),
                ("module", models.CharField(blank=True, default="tz", max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name="pay_item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pi_name", models.CharField(blank=True, default=None, max_length=128)),
                ("active", models.IntegerField(default=1)),
                ("cancelled", models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="teacher",
            fields=[
                (
                    "teacher_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "teacher_identification_number",
                    models.CharField(blank=True, default=None, max_length=24),
                ),
                (
                    "teacher_prefix_th",
                    models.CharField(blank=True, default=None, max_length=48),
                ),
                (
                    "teacher_firstname_th",
                    models.CharField(blank=True, default=None, max_length=128),
                ),
                (
                    "teacher_lastname_th",
                    models.CharField(blank=True, default=None, max_length=128),
                ),
                (
                    "teacher_prefix_eng",
                    models.CharField(blank=True, default=None, max_length=48),
                ),
                (
                    "teacher_firstname_eng",
                    models.CharField(blank=True, default=None, max_length=128),
                ),
                (
                    "teacher_lastname_eng",
                    models.CharField(blank=True, default=None, max_length=128),
                ),
                (
                    "teacher_cover",
                    models.ImageField(default=None, upload_to="images/teacher"),
                ),
                ("teacher_type", models.IntegerField(default=1)),
                ("active", models.IntegerField(default=1)),
                ("crt_date", models.DateTimeField(blank=True, null=True)),
                ("upd_date", models.DateTimeField(blank=True, null=True)),
                ("cancelled", models.IntegerField(default=1)),
                ("module", models.CharField(blank=True, default="tz", max_length=12)),
            ],
        ),
        migrations.AddField(
            model_name="course",
            name="module",
            field=models.CharField(blank=True, default="tz", max_length=12),
        ),
        migrations.AddField(
            model_name="course_event",
            name="module",
            field=models.CharField(blank=True, default="tz", max_length=12),
        ),
        migrations.AddField(
            model_name="register_main",
            name="module",
            field=models.CharField(blank=True, default="tz", max_length=12),
        ),
        migrations.AlterField(
            model_name="student",
            name="student_prefix_eng",
            field=models.CharField(blank=True, default=None, max_length=48),
        ),
        migrations.AlterField(
            model_name="student",
            name="student_prefix_th",
            field=models.CharField(blank=True, default=None, max_length=48),
        ),
        migrations.CreateModel(
            name="user_group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("module", models.CharField(blank=True, default="tz", max_length=12)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_group_ref",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="user_detail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.category_program",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="teacher_income_setting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tis_compensation", models.FloatField(default=0)),
                ("tis_unit", models.CharField(blank=True, default=None, max_length=64)),
                ("tis_quantity", models.IntegerField(default=0)),
                ("tis_sum", models.FloatField(default=0)),
                ("tis_start_date", models.DateField(blank=True, null=True)),
                ("tis_end_date", models.DateField(blank=True, null=True)),
                ("tis_group", models.CharField(blank=True, default="-", max_length=64)),
                ("active", models.IntegerField(default=0)),
                ("crt_date", models.DateTimeField(blank=True, null=True)),
                ("upd_date", models.DateTimeField(blank=True, null=True)),
                (
                    "ev",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.course_event",
                    ),
                ),
                (
                    "pi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.pay_item"
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.teacher"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="category_program_permission",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=app.functions.generateShortId,
                        max_length=24,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "page_route",
                    models.CharField(blank=True, default=None, max_length=64),
                ),
                (
                    "page_label",
                    models.CharField(blank=True, default=None, max_length=64),
                ),
                (
                    "group_value",
                    models.CharField(blank=True, default=None, max_length=64),
                ),
                (
                    "group_label",
                    models.CharField(blank=True, default=None, max_length=64),
                ),
                (
                    "cm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.category_program",
                    ),
                ),
            ],
        ),
    ]
