# Generated by Django 5.1.2 on 2026-07-01 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


POLICIES = [
    {
        "policy_code": "1",
        "policy_name": "นโยบาย ค่า Commission IDC 3%",
        "seq": 1,
        "conditions": [
            {"condition_code": "1.1", "condition_name": "ค่าคอมการขาย 3% แบบแบ่งสัดส่วน", "calc_type": "PRORATA", "seq": 1},
            {"condition_code": "1.2", "condition_name": "ค่าคอมการขาย 3% แบบก้อนเดียว", "calc_type": "LUMPSUM", "seq": 2},
        ],
    },
    {
        "policy_code": "2",
        "policy_name": "นโยบาย จ่ายบุคคลภายนอก",
        "seq": 2,
        "conditions": [
            {"condition_code": "2.1", "condition_name": "ค่าการตลาด (ภายนอก: NT, สมาคม, ชมรม, ศูนย์, สำนัก, อื่นๆ)", "calc_type": "PRORATA", "seq": 1},
            {"condition_code": "2.2", "condition_name": "ค่าที่ปรึกษา หรือ นายหน้า: แนะนำ/นำไปสู่การปิดการขาย", "calc_type": "PRORATA", "seq": 2},
        ],
    },
    {
        "policy_code": "3",
        "policy_name": "นโยบาย จ่ายค่าตอบแทนผู้ปฏิบัติงาน",
        "seq": 3,
        "conditions": [
            {"condition_code": "3.1", "condition_name": "การจัดหากองทุน", "calc_type": "PRORATA", "seq": 1},
            {"condition_code": "3.2", "condition_name": "การจัดเชิงกลยุทธ์: เป้าหมายลูกค้า ออกแบบสื่อการสอน สื่อการตลาด", "calc_type": "PRORATA", "seq": 2},
            {"condition_code": "3.3", "condition_name": "การพัฒนาโปรแกรม และผลิตผลิตภัณฑ์ A", "calc_type": "PRORATA", "seq": 3},
            {"condition_code": "3.4", "condition_name": "การพัฒนาโปรแกรม และผลิตผลิตภัณฑ์ B", "calc_type": "PRORATA", "seq": 4},
            {"condition_code": "3.5", "condition_name": "การติดตั้งและงานที่เกี่ยวข้อง: บันทึกข้อมูลตั้งต้น", "calc_type": "PRORATA", "seq": 5},
            {"condition_code": "3.6", "condition_name": "SUPPORT TEAM: อบรม/ ให้ข้อมูลเชิงลึก/ บริการก่อน-หลังขาย", "calc_type": "PRORATA", "seq": 6},
            {"condition_code": "3.7", "condition_name": "การบริหารจัดการภายในฝ่ายที่เกี่ยวข้อง A", "calc_type": "PRORATA", "seq": 7},
            {"condition_code": "3.8", "condition_name": "การบริหารจัดการภายในฝ่ายที่เกี่ยวข้อง B", "calc_type": "PRORATA", "seq": 8},
            {"condition_code": "3.9", "condition_name": "BACK OFFICE: ทีมงานสำนักงานที่เกี่ยวข้องการขาย/บริการ", "calc_type": "PRORATA", "seq": 9},
        ],
    },
    {
        "policy_code": "4",
        "policy_name": "นโยบาย ค่า Commission IDC",
        "seq": 4,
        "conditions": [
            {"condition_code": "4.1", "condition_name": "PRE SALE: การเปิดการขาย/ ให้บริการ/ นำไปสู่การปิดการขาย", "calc_type": "PRORATA", "seq": 1},
            {"condition_code": "4.2", "condition_name": "CORE TEAM: ทีมงานที่เกี่ยวข้องให้การขาย/บริการสำเร็จ", "calc_type": "PRORATA", "seq": 2},
            {"condition_code": "4.3", "condition_name": "การบริหารจัดการภายในฝ่าย: A", "calc_type": "PRORATA", "seq": 3},
            {"condition_code": "4.4", "condition_name": "การบริหารจัดการภายในฝ่าย: B", "calc_type": "PRORATA", "seq": 4},
            {"condition_code": "4.5", "condition_name": "BACK OFFICE: ทีมงานสำนักงานที่เกี่ยวข้องการขาย/บริการ", "calc_type": "PRORATA", "seq": 5},
        ],
    },
]


def seed_policies(apps, schema_editor):
    commission_policy = apps.get_model("app", "commission_policy")
    commission_condition = apps.get_model("app", "commission_condition")
    for p in POLICIES:
        policy = commission_policy.objects.create(
            policy_code=p["policy_code"], policy_name=p["policy_name"], seq=p["seq"], active=1)
        for c in p["conditions"]:
            commission_condition.objects.create(
                policy=policy,
                condition_code=c["condition_code"],
                condition_name=c["condition_name"],
                calc_type=c["calc_type"],
                seq=c["seq"],
                active=1,
            )


def unseed_policies(apps, schema_editor):
    commission_policy = apps.get_model("app", "commission_policy")
    commission_policy.objects.filter(
        policy_code__in=[p["policy_code"] for p in POLICIES]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='commission_condition',
            fields=[
                ('condition_id', models.AutoField(primary_key=True, serialize=False)),
                ('condition_code', models.CharField(blank=True, default=None, max_length=8)),
                ('condition_name', models.CharField(blank=True, default=None, max_length=255)),
                ('calc_type', models.CharField(blank=True, default='PRORATA', max_length=16)),
                ('seq', models.IntegerField(default=0)),
                ('active', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='commission_policy',
            fields=[
                ('policy_id', models.AutoField(primary_key=True, serialize=False)),
                ('policy_code', models.CharField(blank=True, default=None, max_length=8)),
                ('policy_name', models.CharField(blank=True, default=None, max_length=255)),
                ('seq', models.IntegerField(default=0)),
                ('active', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='commission_payee',
            fields=[
                ('payee_id', models.AutoField(primary_key=True, serialize=False)),
                ('payee_type', models.CharField(blank=True, default=None, max_length=16)),
                ('payee_name', models.CharField(blank=True, default=None, max_length=255)),
                ('bank_name', models.CharField(blank=True, default=None, max_length=128)),
                ('bank_account', models.CharField(blank=True, default=None, max_length=64)),
                ('active', models.IntegerField(default=1)),
                ('crt_date', models.DateTimeField(blank=True, null=True)),
                ('upd_date', models.DateTimeField(blank=True, null=True)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission_payee_teacher', to='app.teacher')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission_payee_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='commission_plan',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_locked', models.IntegerField(default=0)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('crt_date', models.DateTimeField(blank=True, null=True)),
                ('upd_date', models.DateTimeField(blank=True, null=True)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission_plan_locked_by', to=settings.AUTH_USER_MODEL)),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_plans', to='app.register_main')),
                ('rpi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission_plan', to='app.register_payment_items')),
            ],
        ),
        migrations.CreateModel(
            name='commission_payout',
            fields=[
                ('payout_id', models.AutoField(primary_key=True, serialize=False)),
                ('rate', models.FloatField(default=0)),
                ('base_amount', models.FloatField(default=0)),
                ('payee_percent', models.FloatField(blank=True, null=True)),
                ('payout_amount', models.FloatField(default=0)),
                ('status', models.CharField(blank=True, default='PENDING', max_length=16)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('crt_date', models.DateTimeField(blank=True, null=True)),
                ('upd_date', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission_payout_approved_by', to=settings.AUTH_USER_MODEL)),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.commission_condition')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission_payout_paid_by', to=settings.AUTH_USER_MODEL)),
                ('payee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.commission_payee')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='app.commission_plan')),
            ],
        ),
        migrations.CreateModel(
            name='commission_plan_line',
            fields=[
                ('line_id', models.AutoField(primary_key=True, serialize=False)),
                ('rate', models.FloatField(default=0)),
                ('active', models.IntegerField(default=0)),
                ('source', models.CharField(blank=True, default='DEFAULT', max_length=16)),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.commission_condition')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='app.commission_plan')),
            ],
            options={
                'unique_together': {('plan', 'condition')},
            },
        ),
        migrations.CreateModel(
            name='commission_plan_allocation',
            fields=[
                ('alloc_id', models.AutoField(primary_key=True, serialize=False)),
                ('percent', models.FloatField(default=0)),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.commission_payee')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='app.commission_plan_line')),
            ],
        ),
        migrations.AddField(
            model_name='commission_condition',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='app.commission_policy'),
        ),
        migrations.CreateModel(
            name='commission_rule',
            fields=[
                ('rule_id', models.AutoField(primary_key=True, serialize=False)),
                ('rate', models.FloatField(default=0)),
                ('active', models.IntegerField(default=0)),
                ('crt_date', models.DateTimeField(blank=True, null=True)),
                ('upd_date', models.DateTimeField(blank=True, null=True)),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.commission_condition')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_rules', to='app.course')),
            ],
            options={
                'unique_together': {('course', 'condition')},
            },
        ),
        migrations.CreateModel(
            name='commission_rule_allocation',
            fields=[
                ('alloc_id', models.AutoField(primary_key=True, serialize=False)),
                ('percent', models.FloatField(default=0)),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.commission_payee')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='app.commission_rule')),
            ],
        ),
        migrations.RunPython(seed_policies, unseed_policies),
    ]
