# Generated by Django 5.2.15 on 2026-07-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_commission_engine'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_event',
            name='ev_user',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
