# Generated by Django 5.2.15 on 2026-07-02 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_add_ev_user_to_course_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='sale_mode',
            field=models.CharField(blank=True, choices=[('all', 'ทั้งหมด'), ('event', 'มี Event เท่านั้น'), ('noevent', 'ไม่มี Event เท่านั้น')], default='all', max_length=10),
        ),
    ]
