# Generated by Django 5.2.15 on 2026-07-03 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_add_sale_mode_to_course'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='commission_event_rule',
            fields=[
                ('ev_rule_id', models.AutoField(primary_key=True, serialize=False)),
                ('rate', models.FloatField(default=0)),
                ('active', models.IntegerField(default=0)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('crt_date', models.DateTimeField(blank=True, null=True)),
                ('upd_date', models.DateTimeField(blank=True, null=True)),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.commission_condition')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_ev_rules', to='app.course_event')),
            ],
            options={
                'unique_together': {('event', 'condition')},
            },
        ),
        migrations.CreateModel(
            name='commission_event_allocation',
            fields=[
                ('ev_alloc_id', models.AutoField(primary_key=True, serialize=False)),
                ('percent', models.FloatField(default=100)),
                ('amount', models.FloatField(default=0)),
                ('status', models.CharField(default='PENDING', max_length=16)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('crt_date', models.DateTimeField(blank=True, null=True)),
                ('upd_date', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ev_alloc_approved', to=settings.AUTH_USER_MODEL)),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ev_alloc_paid', to=settings.AUTH_USER_MODEL)),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.commission_payee')),
                ('ev_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='app.commission_event_rule')),
            ],
        ),
    ]
