# Generated by Django 5.2.15 on 2026-07-07 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_commission_event_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='er',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salesorders', to='app.register_main'),
        ),
    ]
